import type { CategoryItem } from "@/lib/domain/categories";

export const currentMonth = "Agosto de 2026";

export const demoCategories: CategoryItem[] = (
  [
    { id: "demo-moradia", name: "Moradia", type: "expense", color: "teal" },
    {
      id: "demo-alimentacao",
      name: "Alimentação",
      type: "expense",
      color: "aqua",
    },
    {
      id: "demo-transporte",
      name: "Transporte",
      type: "expense",
      color: "green",
    },
    { id: "demo-saude", name: "Saúde", type: "expense", color: "coral" },
    {
      id: "demo-educacao",
      name: "Educação/Trabalho",
      type: "expense",
      color: "blue",
    },
    { id: "demo-igreja", name: "Igreja", type: "expense", color: "amber" },
    {
      id: "demo-lazer",
      name: "Lazer/Vida pessoal",
      type: "expense",
      color: "coral",
    },
    { id: "demo-dividas", name: "Dívidas", type: "expense", color: "teal" },
    { id: "demo-salario", name: "Salário", type: "income", color: "green" },
    {
      id: "demo-receita-extra",
      name: "Receita extra",
      type: "income",
      color: "green",
    },
    {
      id: "demo-reembolso",
      name: "Reembolso",
      type: "income",
      color: "aqua",
    },
  ] as const
).map((category) => ({
  ...category,
  isSystem: true,
  archived: false,
}));

export const dashboard = {
  safeToSpendCents: 284500,
  incomeCents: 1000000,
  committedCents: 665500,
  paidCents: 348000,
  budgetRemainingCents: 284500,
  invoice: {
    amountCents: 168900,
    due: "12/08",
    goalCents: 300000,
    status: "Aberta",
  },
  savings: {
    name: "Reserva de emergência",
    currentCents: 785000,
    targetCents: 1500000,
  },
};

export const budgetRows = [
  {
    name: "Alimentação",
    allocated: 100000,
    committed: 88500,
    paid: 27000,
    state: "attention" as const,
  },
  {
    name: "Educação/Trabalho",
    allocated: 65000,
    committed: 65000,
    paid: 0,
    state: "critical" as const,
  },
  {
    name: "Moradia",
    allocated: 150000,
    committed: 150000,
    paid: 150000,
    state: "critical" as const,
  },
  {
    name: "Transporte",
    allocated: 70000,
    committed: 38500,
    paid: 21500,
    state: "normal" as const,
  },
  {
    name: "Igreja",
    allocated: 90000,
    committed: 62000,
    paid: 62000,
    state: "normal" as const,
  },
  {
    name: "Lazer/Vida pessoal",
    allocated: 80000,
    committed: 41000,
    paid: 25000,
    state: "normal" as const,
  },
];

export const transactions = [
  {
    id: "1",
    date: "12 AGO",
    occurrenceDate: "2026-08-12",
    description: "Internet",
    category: "Moradia",
    method: "Pix · Santander",
    responsible: "Gabriel",
    amountCents: -11990,
    status: "pending" as const,
    updatedAt: "2026-08-12T12:00:00Z",
  },
  {
    id: "2",
    date: "11 AGO",
    occurrenceDate: "2026-08-11",
    description: "Combustível",
    category: "Transporte",
    method: "Crédito · Santander",
    responsible: "Brunna",
    amountCents: -18500,
    status: "pending" as const,
    updatedAt: "2026-08-11T12:00:00Z",
  },
  {
    id: "3",
    date: "08 AGO",
    occurrenceDate: "2026-08-08",
    description: "Salário Brunna",
    category: "Salário",
    method: "Pix · Santander",
    responsible: "Brunna",
    amountCents: 380000,
    status: "pending" as const,
    updatedAt: "2026-08-08T12:00:00Z",
  },
  {
    id: "4",
    date: "06 AGO",
    occurrenceDate: "2026-08-06",
    description: "Aluguel",
    category: "Moradia",
    method: "Pix · Santander",
    responsible: "Gabriel",
    amountCents: -150000,
    status: "paid" as const,
    updatedAt: "2026-08-06T12:00:00Z",
  },
  {
    id: "5",
    date: "05 AGO",
    occurrenceDate: "2026-08-05",
    description: "Aporte mensal",
    category: "Transferência",
    method: "Santander → Reserva",
    responsible: "Gabriel",
    amountCents: -50000,
    status: "paid" as const,
    updatedAt: "2026-08-05T12:00:00Z",
  },
  {
    id: "6",
    date: "04 AGO",
    occurrenceDate: "2026-08-04",
    description: "Mercado do mês",
    category: "Alimentação",
    method: "Crédito · Santander",
    responsible: "Brunna",
    amountCents: -61500,
    status: "pending" as const,
    updatedAt: "2026-08-04T12:00:00Z",
  },
  {
    id: "7",
    date: "03 AGO",
    occurrenceDate: "2026-08-03",
    description: "Faculdade · 3/8",
    category: "Educação/Trabalho",
    method: "Crédito · Santander",
    responsible: "Gabriel",
    amountCents: -10001,
    status: "pending" as const,
    updatedAt: "2026-08-03T12:00:00Z",
  },
];

export const weeks = [
  { label: "1–2 ago", allocated: 10000, spent: 7200 },
  { label: "3–9 ago", allocated: 22500, spent: 19800 },
  { label: "10–16 ago", allocated: 22500, spent: 12400 },
  { label: "17–23 ago", allocated: 22500, spent: 0 },
  { label: "24–30 ago", allocated: 17500, spent: 0 },
  { label: "31 ago", allocated: 5000, spent: 0 },
];

export const projection = [
  {
    month: "Ago",
    income: 1000000,
    recurring: 407000,
    invoices: 168900,
    extras: 28000,
    savings: 50000,
    balance: 346100,
  },
  {
    month: "Set",
    income: 1000000,
    recurring: 407000,
    invoices: 143400,
    extras: 0,
    savings: 50000,
    balance: 399600,
  },
  {
    month: "Out",
    income: 1000000,
    recurring: 407000,
    invoices: 112700,
    extras: 0,
    savings: 50000,
    balance: 430300,
  },
  {
    month: "Nov",
    income: 1000000,
    recurring: 407000,
    invoices: 106200,
    extras: 0,
    savings: 50000,
    balance: 436800,
  },
  {
    month: "Dez",
    income: 1000000,
    recurring: 407000,
    invoices: 102000,
    extras: 80000,
    savings: 50000,
    balance: 361000,
  },
  {
    month: "Jan",
    income: 1000000,
    recurring: 407000,
    invoices: 100000,
    extras: 0,
    savings: 50000,
    balance: 443000,
  },
];

export const accounts = [
  {
    id: "a1",
    name: "Santander",
    type: "checking" as const,
    institution: "Santander",
    balanceCents: 663000,
    updated: "Hoje, 12:40",
    countsAsReserve: false,
  },
  {
    id: "a2",
    name: "Mercado Pago",
    type: "wallet" as const,
    institution: "Mercado Pago",
    balanceCents: 60000,
    updated: "Ontem",
    countsAsReserve: false,
  },
  {
    id: "a3",
    name: "Dinheiro",
    type: "cash" as const,
    institution: "",
    balanceCents: 18000,
    updated: "08/08",
    countsAsReserve: false,
  },
  {
    id: "a4",
    name: "Reserva de Emergência",
    type: "savings" as const,
    institution: "Santander",
    balanceCents: 785000,
    updated: "05/08",
    countsAsReserve: true,
  },
];

export const cards = [
  {
    id: "c1",
    name: "Santander",
    institution: "Santander",
    network: "visa" as const,
    lastFour: "2048",
    holder: "Gabriel",
    closingDay: 7,
    dueDay: 12,
    bankLimitCents: 2300000,
    monthlyGoalCents: 300000,
  },
];
